name: "🎉 Release new version"

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Release type
        options:
          - "--release-as patch"
          - "--release-as minor"
  push:
    branches:
      - master
    paths:
      - "packages/daisyui/**"

jobs:
  run-tests:
    name: 🧪 Tests
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      filter: ""

  build-publish:
    name: 🔨 Build + 🚀 Publish
    needs: run-tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build package
        run: bun run build

      - name: Run release command
        run: |
          git config --local user.email "pouya.saadeghi@gmail.com"
          git config --local user.name "Pouya Saadeghi"
          cd packages/daisyui
          bunx commit-and-tag-version --infile ../../CHANGELOG.md ${{ inputs.release-type }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to NPM
        if: github.repository == 'saadeghi/daisyui'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          cd packages/daisyui
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_LOGLEVEL: verbose

  deploy-docs:
    name: 📘 Docs
    needs: build-publish
    uses: ./.github/workflows/deploy-docs.yml
    secrets: inherit

  write-release-notes:
    name: 📝 Release notes
    needs: deploy-docs
    uses: ./.github/workflows/write-release-notes.yml
    secrets: inherit
